Repository Active-Outre-Mer-Dev/sxm-quiz, pull requests merged in 2023-07, with the labels that each got.

#9 Article additon
  src/content/indigenous-heritage-of-saint-martin.md
  src/content/saint-martin-a-tale-of-two-cultures.md
  src/content/saint-martin-a-tourist-haven.md
  src/content/saint-martin-carnival-origins.md
  src/content/saint-martin-national-bird.md
  src/content/saint-martin-topography.md
  src/content/slavery-and-emancipation-in-saint-martin.md
Labels: area: Articles, created-by: SXM Quiz Core team, new article

#11 [feat] - improve command palette
  src/app/learn/[category]/page.tsx
  src/app/learn/page.tsx
  src/components/navbar.tsx
  src/components/search-wrapper.tsx
  src/components/searchbar-loading.tsx
  src/components/searchbar.tsx
Labels: enhancement, created-by: SXM Quiz Core team

#12 [feat] - make learn page filters functional
  src/app/learn/[category]/page.tsx
  src/app/learn/_components/all-articles.tsx
  src/app/learn/_components/article-filter.tsx
  src/app/learn/_components/article-list.tsx
  src/app/learn/_components/article.tsx
  src/app/learn/_components/nav-link.tsx
  src/app/learn/_components/random-facts.tsx
  src/app/learn/article-list.tsx
  src/app/learn/client.tsx
  src/app/learn/layout.tsx
  src/app/learn/page.tsx
Labels: enhancement

#13 Updated data-lists.json
  src/data-lists.json
Labels: enhancement, created-by: SXM Quiz Core team

#15 [chore] - update blog design
  src/app/blog/[slug]/_components/author.tsx
  src/app/blog/[slug]/_components/newsletter.tsx
  src/app/blog/[slug]/_components/share-media.tsx
  src/app/blog/[slug]/_components/toc.tsx
  src/app/blog/[slug]/page.tsx
  src/app/blog/page.tsx
  src/app/layout.tsx
Labels: created-by: SXM Quiz Core team

#16 Update indigenous-heritage-of-saint-martin.md
  src/content/indigenous-heritage-of-saint-martin.md
  src/content/saint-martin-a-haven-for-flora-and-fauna.md
  src/content/saint-martin-a-tale-of-two-cultures.md
  src/content/saint-martin-a-tourist-haven.md
  src/content/saint-martin-carnival-origins.md
  src/content/saint-martin-national-bird.md
  src/content/saint-martin-topography.md
  src/content/slavery-and-emancipation-in-saint-martin.md
Labels: bug

#20 [chore] - fix bold text
  src/content/what-is-saint-martin.md
Labels: bug, typo

#24 [feat] - setup event tracking
  package.json
  pnpm-lock.yaml
  src/app/api/events/route.ts
  src/app/learn/[category]/[slug]/article-event.tsx
  src/app/learn/[category]/[slug]/page.tsx
  src/app/quiz/[slug]/_components/container/container.context.tsx
  src/app/quiz/[slug]/_components/container/index.tsx
  src/app/quiz/[slug]/_components/list-quiz/index.tsx
  src/app/quiz/[slug]/_components/question-quiz/index.tsx
  src/lib/send-event.ts
Labels: enhancement, created-by: SXM Quiz Core team

#25 [fix] - make sure data isnt cached for dynamic quiz page
  src/app/api/events/route.ts
  src/app/quiz/[slug]/page.tsx
Labels: bug, created-by: SXM Quiz Core team, area: Quizzes
